on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Title
          body: Body
          assignees: kenro17
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO
